name: pdv
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  intl: ^0.20.2
  uuid: ^4.5.2
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  #Tests
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  #Database
  drift_dev: ^2.31.0
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/seed.json
    - assets/images/
